drop database if exists AWSObjects;
drop type if exists AWSObjectState cascade;
drop table if exists AWSObjectTable;
drop type if exists AWSLogLevel cascade;
drop table if exists AWSLogTable;
drop index if exists AWSLogTimeIndex;
drop table if exists AWSStatusTable;
drop index if exists AWSStatusPIDIndex;
drop materialized view if exists AWSObjectTableTotals;
drop function if exists humanReadableBytes(size bigint) cascade;
drop function if exists daySpan(fromDate timestamptz, toDate timestamptz) cascade;
drop table if exists AWSParameterTable;
